spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ibe
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
