spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ibe
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
